### ISSUE TITLE
Does not upscale the image (500 Internal Server Error)

### ISSUE THREAD

**Issue by LeonWGal** [ellypaws/stable-diffusion-discord-bot#10]
At any attempt, it does not increase the resolution on the image. Below are the error messages and the log

> Error
> Multiple errors have occurred:
> I'm sorry, but I had a problem upscaling your image.
> unexpected status code: 500 Internal Server Error

```
Passing '{"sd_model_checkpoint":"sd\\1 Best\\zmixTooniverseXL_beta1.safetensors","sd_vae":"sdxl_vae.safetensors","sd_hypernetwork":"None"}' to sdapi/v1/options
2024/10/12 17:34:42 Response status: &{200 OK 200 HTTP/1.1 1 1 map[Content-Length:[4] Content-Type:[application/json] Date:[Sat, 12 Oct 2024 08:34:41 GMT] Server:[uvicorn]] 0xc0015367c0 4 [] false false map[] 0xc000bb03c0 <nil>}

```

**Comment by LeonWGal** [comment]
I have a VPN running on the host computer because of the Discord banned in my country

**Comment by ellypaws** [comment]
This is most likely because you don't have R-ESRGAN 2x+. You can download this through https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth and put it in the folder `models/RealESRGAN`

Alternatively you can change the code in https://github.com/ellypaws/stable-diffusion-discord-bot/blob/e27c71d4967392d2980cfd3c4d2da674dd224df7/queue/stable_diffusion/upscale.go#L79-L84 to a different upscaler, e.g. `Latent`

The latest commit in dev 1efed362c04f704ab27be0a6669e2a5300bfd3f8 should have better error message on upscale
